export const PAGINATION_MIN_LIMIT = 6;
export const PAGINATION_MAX_LIMIT = Number.MAX_SAFE_INTEGER;
export const PAGINATION_MIN_PAGE = 1;
export const DEFAULT_ALL = 'ALL';
export const MAXIMUM_THE_NUMBER_OF_GENERATIONS = 3;
