version: '3.9'

services:
  backend:
    image: miraijr/artist_be:main
    container_name: artist_be
    env_file:
      - .docker.env
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - redis
      - mysql
    volumes:
      - ./artist-be-log/logs:/src/../logs
    networks:
      - artist_network

  redis:
    container_name: redis_cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/artist_be/data
    networks:
      - artist_network

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: artist
      MYSQL_USER: artist_database_191
      MYSQL_PASSWORD: datn191*11
      MYSQL_ROOT_PASSWORD: datn191*11root
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./deploy/script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - artist_network

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk
      - artist_network

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
    networks:
      - elk
      - artist_network

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk
      - artist_network

  filebeat:
    build:
      context: ./elasticsearch
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - ./artist-be-log/logs:/src/../logs
    networks:
      - elk
      - artist_network

volumes:
  redis:
    driver: local
  mysql-data:
    driver: local
  elastic_data:
    driver: local

networks:
  elk:
  artist_network:
