name: eslint check source code
run-name: Run ESLint to check code formatting

on: [push, pull_request]

jobs:
  check-eslint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: review dog check elsint
        uses: ./.github/actions/review-dog
