name: unittest

permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - 'main'

jobs: 
  deploy-unittest-coverage-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: npm install
      - name: Build test coverage
        run: npm run test:cov

      - name: Deploy coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: coverage

