name: Push images to docker hub
run-name: Push images to docker hub

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  push-images-to-docker-hub:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push images to docker hub
        uses: ./.github/actions/docker-hub-action
